### ISSUE TITLE
Upload trace key button unresponsive

### ISSUE THREAD

**Issue by rachyandco** [notifyme-app/notifyme-app-android#7]
After having scanned a QR-code, entering both start time and end time, the "upload trace key" button remains unresponsive. It does seems to be greyed out.

![photo_2020-11-13_10-38-11](https://user-images.githubusercontent.com/2358699/99057697-726ffd80-259c-11eb-9507-c1be44cd71b8.jpg)

Android: 7.1.2
LineageOs

**Comment by kellenberger** [comment]
@rachyandco I am not able to reproduce this, can you give me some more information? For example, did you encounter this behavior multiple times? Do you hit the upload button, before getting stuck?

The button is disabled after uploading the form to avoid multiple submits. A loading indicator would probably make that clearer.
However after the request has finished, it should either show a success or an error message and the button should be re-enabled.

**Comment by rachyandco** [comment]
Weird, i cannot seem to reproduce. i close it for now,
